name: ci/cd proccess

on:
  push:
    branches:
      - 'master'
jobs:
  unit-test:
    name: unit-test
    runs-on: ubuntu-latest
    steps: # Mau ngapain
    - uses: actions/checkout@v2
    - name: setup golang
      uses: actions/checkout@v2
      with: 
        go-version: 1.17
    - name: running unit test
      run: go test ./... -cover # proses command seperti biasa
  build-push-docker: 
    name: build image and push docker hub 
    runs-on: ubuntu-latest 
    needs: unit-test 
    steps: 
      - uses: actions/checkout@v2 
      - name: generate config file 
        env: 
          CONFIG: ${{secrets.APP_CONFIG}} 
        run: | 
          rm -fd -R config/ && mkdir config && echo "$CONFIG" > ./config/.env
      - name: build image
        run: docker build -t widyaadebagus/webstore-golang:1.0 . 
      - name: login docker hub 
        uses: docker/login-action@v1
        with: 
          username: ${{secrets.DOCKER_USERNAME}} 
          password: ${{secrets.DOCKER_PASSWORD}} 
      - name: push docker registry 
        run: docker push widyaadebagus/webstore-golang:1.0
  deployment-ec2:
    name: "Deploy to ec2 from registry docker hub"
    runs-on: ubuntu-latest
    needs: build-push-docker
    steps:
      - uses: actions/checkout@v2 
      - name: configuration SSH
        env:
          SSH_USER: ${{ secrets.SSH_USERNAME }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/widyaadeb@gmailcom.pem
          chmod 400 ~/.ssh/widyaadeb@gmailcom.pem
          cat >>~/.ssh/config <<END
          Host development
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/widyaadeb@gmailcom.pem
            StrictHostKeyChecking=no
          END
      - name: Connect EC2 & Remove All Container & Pull from Registry & Start
        run: ssh development 'docker rm -f $(docker ps -a -q) || true && docker pull widyaadebagus/webstore-golang:1.0 && docker run -d -p 8000:8000 --name=webstore widyaadebagus/webstore-golang:1.0 && docker run -d -p 65432:5432 -e POSTGRES_USER=testuser -e POSTGRES_PASSWORD=yourpassword -e POSTGRES_DB=storedb --name=postgresql postgres:10-alpine'
