name: ci/cd proccess

on:
  push:
    branches:
      - 'master'
jobs:
  unit-test:
    name: unit-test
    runs-on: ubuntu-latest
    steps: # Mau ngapain
    - uses: actions/checkout@v2
    - name: setup golang
      uses: actions/checkout@v2
      with: 
        go-version: 1.17
    - name: running unit test
      run: go test ./... -cover # proses command seperti biasa
  build-push-docker: 
    name: build image and push docker hub 
    runs-on: ubuntu-latest 
    needs: unit-test 
    steps: 
      - uses: actions/checkout@v2 
      - name: generate config file 
        env: 
          CONFIG: ${{secrets.APP_CONFIG}} 
          run: | 
            echo "$CONFIG" > ./app.config.json 
      - name: build image
        run: docker build -t widyaadebagus/webstore-golang:1.0 . 
      - name: login docker hub 
        uses: docker/login-action@v1
        with: 
          username: ${{secrets.DOCKER_USERNAME}} 
          password: ${{secrets.DOCKER_PASSWORD}} 
      - name: push docker registry 
        run: docker push widyaadebagus/webstore-golang:1.0